Parameters:
  SGforInstances:
    Type: String
    Description: Security Group for instances
  PublicSubnet1:
    Type: String
    Description: Public Subnet 1
  PublicSubnet2:
    Type: String
    Description: Public Subnet 2
  VPC:
    Type: String
    Description: Imported VPC

Resources:
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SGforInstances
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Type: network

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      VpcId: !Ref VPC

  Listener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP

Outputs:
  TargetGroupArn:
    Description: Target group ARN
    Value: !Ref TargetGroup
  DNSName:
    Description: DNSName for NLB
    Value: !GetAtt NLB.DNSName