AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket

Outputs:
  S3BucketName:
    Description: The S3 bucket name
    Value: !Ref S3Bucket
