Parameters:
  S3Bucket:
    Type: String
    Default: https://strike-gain.s3.ap-southeast-1.amazonaws.com

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/vpc-stack.yml"

  SSMHost:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SGforInstances:
          Fn::GetAtt:
            - VPCStack
            - Outputs.SGforVPC
        PublicSubnet1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PublicSubnet1
      TemplateURL: !Sub "${S3Bucket}/ssmhost.yml"

  NLBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/nlb-stack.yml"
      Parameters:
        SGforInstances:
          Fn::GetAtt:
            - VPCStack
            - Outputs.SGforVPC
        PublicSubnet1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PublicSubnet2
        VPC:
          Fn::GetAtt:
            - VPCStack
            - Outputs.VPC

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/ec2-stack.yml"
      Parameters:
        PrivateSubnet1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet2
        SGforInstances:
          Fn::GetAtt:
            - VPCStack
            - Outputs.SGforVPC
        TargetGroupArn:
          Fn::GetAtt:
            - NLBStack
            - Outputs.TargetGroupArn

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/rds-stack.yml"
      Parameters:
        PrivateSubnet1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet2
        VPC:
          Fn::GetAtt:
            - VPCStack
            - Outputs.VPC

  VPCEndpoints:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/vpc-endpoints.yml"
      Parameters:
        VPC:
          Fn::GetAtt:
            - VPCStack
            - Outputs.VPC
        PrivateSubnet1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateSubnet2
        SGforInstances:
          Fn::GetAtt:
            - VPCStack
            - Outputs.SGforVPC
        PrivateRouteTable1:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateRouteTable1
        PrivateRouteTable2:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateRouteTable2

  CloudFrontPlusS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Bucket}/cloudfront-plus-s3-stack.yml"
      Parameters:
        DNSName:
          Fn::GetAtt:
            - NLBStack
            - Outputs.DNSName